using System.IO;

namespace ServerTools
{
    class HowToSetup
    {
        public static bool IsEnabled = true;
        private const string file = "HowToSetup.xml";
        private static string filePath = string.Format("{0}/{1}", API.ConfigPath, file);
        private const double version = 6.4;

        public static void HowTo()
        {
            using (StreamWriter sw = new StreamWriter(filePath))
            {
                sw.WriteLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                sw.WriteLine("ServerTools - How to setup ServerTools");
                sw.WriteLine(string.Format("This was drafted for version \"{0}\"/>", version));
                sw.WriteLine();
                sw.WriteLine("ServerTools was coded and tested under a Windows operating system. It should operate on other major O.S. but if you find bugs, report them to");
                sw.WriteLine("https://github.com/dmustanger/7dtd-ServerTools/issues");
                sw.WriteLine();
                sw.WriteLine("This version is compatible with 7 Days to Die: Alpha 16.");
                sw.WriteLine();
                sw.WriteLine("Open the ServerToolsConfig.xml found in the same directory as this file. You will need to enable and set each tools options to match your server preferences.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"AdminChatCommands\" Enable=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Adminstrators can use chat to send administrators a ingame chat message. Type @admins (message) to use. Only online administrators will receive the message.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"AdminList\" Enable=\"False\" AdminLevel=\"0\" ModLevel=\"1\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for AdminLevel");
                sw.WriteLine("Set a numeric value for ModLevel");
                sw.WriteLine();
                sw.WriteLine("Type /admins or !admins in chat to get a response showing the currently online administrators and moderators based on the ServerAdmin.xml. Setting AdminLevel to 2 would show all online administrators");
                sw.WriteLine("tier 0-2 as admin in the chat response. Setting ModLevel to 6 would show all online moderators tier 3 through 6 as mods in the chat response.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"AdminNameColoring\" Enable=\"True\" AdminLevel=\"0\" AdminPrefix=\"(ADMIN)\" AdminColor=\"[FF0000]\" ModeratorLevel=\"1\" ModeratorPrefix=\"(MOD)\" ModeratorColor=\"[008000]\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for AdminLevel");
                sw.WriteLine("Set a value of your choice in paranthesis for AdminPrefix");
                sw.WriteLine("Set a color using a html value in brackets for AdminColor");
                sw.WriteLine("Set a numeric value for ModeratorLevel");
                sw.WriteLine("Set a value of your choice in paranthesis for ModeratorPrefix");
                sw.WriteLine("Set a color using a html value in brackets for ModeratorColor");
                sw.WriteLine();
                sw.WriteLine("Administrators that are the correct tier level will have their chat show with a prefex and color when using in game chat based on the ServerAdmin.xml");
                sw.WriteLine("Moderators that are the correct tier level will have their chat show with a prefex and color when using in game chat based on the ServerAdmin.xml");
                sw.WriteLine("Setting AdminLevel to 2 and ModeratorLevel to 6 would show tier 0-2 as Administrators and tier 3-6 as Moderators.");
                sw.WriteLine("Leaving the prefix blank will still show the color but no prefix before their name.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"AnimalTracking\" Enable =\"False\" AlwaysShowResponse =\"False\" DelayBetweenUses =\"60\" MinimumSpawnRadius =\"20\" MaximumSpawnRadius =\"30\" EntityId =\"59, 60, 61\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set True or False for AlwaysShowResponse");
                sw.WriteLine("Set a numeric value for DelayBetweenUses");
                sw.WriteLine("Set a numeric value for MinimumSpawnRadius");
                sw.WriteLine("Set a numeric value for MaximumSpawnRadius");
                sw.WriteLine("Set a numeric values for EntityId");
                sw.WriteLine();
                sw.WriteLine("Type /animaltracking, /track, !animaltracking or !track in chat to get a animal to spawn with in the radius set.");
                sw.WriteLine("Set any animals in the config to the list of Id so they can potentially spawn. Separate entries with a comma.");
                sw.WriteLine("Entity Id can be found in game by typing spawnentity in the console. This will respond with a list of entity and their corresponding Id.");
                sw.WriteLine("The delay is the time that must pass before the command can be used again. The delay is in minutes.");
                sw.WriteLine("Players will receive an in game message saying they have tracked down an animal to with in the radius it spawned at.");
                sw.WriteLine("Recommend experimenting with radius to find one that suits your preference.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"AnnounceInvalidItemStack\" Enable =\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Automatically checks players inventory for invalid stack sizes. The player will receive a message telling them they have an invalid stack and a log will be made to the output_log.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"AutoSaveWorld\" Enable =\"False\" DelayBetweenWorldSaves =\"15\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Automatically begins a save of the world every time the DelayBetweenWorldSaves expires.");
                sw.WriteLine("This save process will repeat.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"AutoShutdown\" Enable =\"False\" CountdownTimer =\"5\" DelayBeforeShutdown =\"60\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for CountdownTimer");
                sw.WriteLine("Set a numeric value for DelayBeforeShutdown");
                sw.WriteLine();
                sw.WriteLine("Automatically begins the shutdown process for the server after the DelayBeforeShutdown time runs out.");
                sw.WriteLine("Begins a warning of the coming shutdown with a timer based on the CountdownTimer after the DelayBeforeShutdown time has run out.");
                sw.WriteLine("Saves the world at one minute remaining of the count down and gives the players a warning not to exchange items or build during the final minute.");                
                sw.WriteLine("If the server is set as a service on the host hardware, it will automatically restart. ServerTools can not automatically restart a server.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"BadWordFilter\" Enable =\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a BadWords.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Filters out bad words or symbols from chat matching the list in BadWords.xml");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Bloodmoon\" Enable =\"False\" ShowOnSpawn =\"False\" ShowOnRespawn =\"False\" AutoShowBloodmoonDelay =\"30\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set True or False for ShowOnSpawn");
                sw.WriteLine("Set True or False for ShowOnRespawn");
                sw.WriteLine("Set a numeric value for AutoShowBloodmoonDelay");
                sw.WriteLine();
                sw.WriteLine("Displays the amount of days before the next bloodmoon in chat.");
                sw.WriteLine("Typing /bloodmoon in chat will respond with the remaining days until the next bloodmoon.");
                sw.WriteLine("Setting ShowOnSpawn will display the remaining days to a player that has just logged into the server.");
                sw.WriteLine("Setting ShowOnRespawn will display the remaining days to a player that has just died, teleported, traveled, or triggered any respawn of their character.");
                sw.WriteLine("AutoShowBloodmoonDelay controls the minutes that will pass before the bloodmoon message shows automatically in chat for all players.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"ChatResponseColor\" Color =\"[00FF00]\" />");
                sw.WriteLine();
                sw.WriteLine("Set a color using a html value in brackets for Color");
                sw.WriteLine();
                sw.WriteLine("This is the color that all chat command responses will respond with and general ServerTools based messages. Always enabled.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"ClanManager\" Enable =\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Enables the clan manager. Players can control it via chat.");
                sw.WriteLine("Commands available are: /clancommands, /clanadd, /clandel, /claninvite, /clanaccept, /clandecline, /clanremove, /clanpromote, /clandemote, /clan, if it starts with /c.");
                sw.WriteLine("Players can create and manage a clan with these various commands.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"CustomCommands\" Enable=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a CustomCommands.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Allows custom commands to be used via chat. Example: The player can type /market and it runs \"tele {SteamId} 0 -1 5\" based on the response the admin has setup.");
                sw.WriteLine("Delays are available for the first ten entries in the list only.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Day7\" Enable=\"False\" DaysUntilHorde=\"7\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for DaysUntilHorde");
                sw.WriteLine();
                sw.WriteLine("Enables the chat commands /day and /day7. Using these will respond with the days left until a horde night as well as the current server FPS, count of mobs, animals,");
                sw.WriteLine("minibikes, and supply crates spawned in the world.");
                sw.WriteLine("If your server uses a horde schedule that is not every 7 days, put the custom value under days until horde.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"DonatorNameColoring\" Enable=\"False\" DonatorLevel1=\"100\" DonatorLevel2=\"101\" DonatorLevel3=\"102\" DonatorPrefix1=\"(DON)\" DonatorPrefix2=\"(DON)\" DonatorPrefix3=\"(DON)\" DonatorColor1=\"[009000]\" DonatorColor2=\"[FF66CC]\" DonatorColor3=\"[E9C918]\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for DonatorLevel1");
                sw.WriteLine("Set a numeric value for DonatorLevel2");
                sw.WriteLine("Set a numeric value for DonatorLevel3");
                sw.WriteLine("Set a value of your choice in paranthesis for DonatorPrefix1");
                sw.WriteLine("Set a value of your choice in paranthesis for DonatorPrefix2");
                sw.WriteLine("Set a value of your choice in paranthesis for DonatorPrefix3");
                sw.WriteLine("Set a color using a html value in brackets for DonatorColor1");
                sw.WriteLine("Set a color using a html value in brackets for DonatorColor2");
                sw.WriteLine("Set a color using a html value in brackets for DonatorColor3");
                sw.WriteLine();
                sw.WriteLine("Players listed on the ReservedSlots.xml with a valid expiration time remaining will have their chat color alter and a prefix added to match what is listed in the config when they have turned it on.");
                sw.WriteLine("Do not use the same levels for each donator. You can set them all as one color if you wish to or three unique ones.");
                sw.WriteLine("Do not use levels that match those used by admins or moderators.");
                sw.WriteLine("Players can type /doncolor in chat to enable their color and prefix settings. If they continue to use /doncolor, it will rotate through the levels and then off.");
                sw.WriteLine("If a player's expiry time has passed, they will no longer show with a color or prefix in chat. Using /doncolor at this point will alert them to their time expiring and when.");
                sw.WriteLine("Leaving the prefix blank will still show the color but no prefix before their name.");
                sw.WriteLine("While enabled, the player will show in your ServerAdmin.xml. Do not be alarmed. For this reason, make sure you do not set them to the same levels as Admins or Mods. The default is typically best at 100, 101, and 102");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"EntityUndergroundCheck\" Enable=\"False\" AlertAdmin=\"False\" AdminLevel=\"0\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set True or False for AlertAdmin");
                sw.WriteLine("Set a numeric value for AdminLevel");
                sw.WriteLine();
                sw.WriteLine("This tool checks for entities underground and detects if they require being sent to the surface such as a falling back pack or minibike.");
                sw.WriteLine("It will automatically attempt to send the detected entity to the world surface.");
                sw.WriteLine("If an entity is detected underground and can not be sent to the surface while AlertAdmin is set to true, a message will be sent to online admins that match the required level. The message has the coords of the entity.");
                sw.WriteLine("Setting AlertAdmin to 4 would send the alert to all admins or mods listed as tier 0-4.");
                sw.WriteLine("Detections are logged out to the servers default output_log file.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"FamilyShareAccount\" Enable=\"False\" AdminLevel=\"0\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for AdminLevel");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a FamilyShareAccount.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Players joining the server while using a family share account are detected and kicked.");
                sw.WriteLine("A players steam Id can be added to FamilyShareAccount.xml which allows them to join. Each family share account must be authorized in this manner. A family share account steamId does not match the ownerId.");               
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"FirstClaimBlock\" Enable=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Players can type /claim to receive a claim block but only once.");
                sw.WriteLine("This is used to help prevent claim block grief with noobs especially on PVP servers.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"FlightCheck\" Enable=\"False\" AdminLevel=\"0\" MaxPing=\"300\" MaxHeight=\"2\" KillPlayer=\"False\" Announce=\"False\" JailEnabled=\"False\" KickEnabled=\"False\" BanEnabled=\"False\" DaysBeforeLogDelete=\"5\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for AdminLevel");
                sw.WriteLine("Set a numeric value for MaxPing");
                sw.WriteLine("Set a numeric value for MaxHeight");
                sw.WriteLine("Set True or False for KillPlayer");
                sw.WriteLine("Set True or False for Announce");
                sw.WriteLine("Set True or False for JailEnabled");
                sw.WriteLine("Set True or False for KickEnabled");
                sw.WriteLine("Set True or False for BanEnabled");
                sw.WriteLine("Set a numeric value for DaysBeforeLogDelete");
                sw.WriteLine();
                sw.WriteLine("Autodetects a player flying in the air. Does not detect them underground. If they are not moving, it will not detect them flying. This is to prevent false positives.");
                sw.WriteLine("Detections are written to a log file for admin review.");
                sw.WriteLine("The admin level is the tier a player is ignored by the detection.");
                sw.WriteLine("MaxPing is the ping a player must hit before the detector ignores them. This is to prevent false positives during lag spikes from the player or server.");
                sw.WriteLine("MaxHeight controls how far off the ground a player can be before detected. Find the best setting for your server between lag and riding minibikes down hills or slopes.");
                sw.WriteLine("The detector knows if a player is falling and will skip them.");
                sw.WriteLine("Multiple penalties are available by setting true for the appropriate punishment. All punishments can be enabled for a K.O. punch.");
                sw.WriteLine("Log files will auto delete themselves after a set amount of days. DaysBeforeLogDelete controls the amount of days.");
                sw.WriteLine("*Note* This tool is based around Coppi's mod player flight check and modified for ServerTools and automation.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Gimme\" Enable=\"False\" DelayBetweenUses=\"1\" AlwaysShowResponse=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for DelayBetweenUses");
                sw.WriteLine("Set True or False for AlwaysShowResponse");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a Gimme.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Players can type /gimme to initiate a free item from the gimme list.");
                sw.WriteLine("The gimme.xml contains a list of all the items a player can receive from using /gimme.");
                sw.WriteLine("A delay can be set so players must wait that period of time before using /gimme again.");
                sw.WriteLine("Setting AlwaysShowResponse to true will force all gimme uses to respond publicly regardless of the player using the private or public chat command trigger.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"HatchElevatorDetector\" Enable=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Auto detects a player that has used hatches as an elevator to reach the surface or top of their tower faster.");
                sw.WriteLine("Players caught using this are stunned and their leg is broken.");
                sw.WriteLine("A message will also show for the player telling them they are stunned and broke a leg while smashing through hatches.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"HighPingKicker\" Enable=\"False\" Maxping=\"250\" SamplesNeeded=\"0\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for Maxping");
                sw.WriteLine("Set a numeric value for SamplesNeeded");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a HighPingImmunity.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Players who have too high of a ping will be kicked from the server automatically.");
                sw.WriteLine("MaxPing is the limit a player can ping at before being flagged for kick.");
                sw.WriteLine("SamplesNeeded control the amount of times in a row a player must fail the ping check before the auto kick initiates.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"InfoTicker\" Enable=\"False\" DelayBetweenMessages=\"2\" Random=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for DelayBetweenMessages");
                sw.WriteLine("Set True or False for Random");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a InfoTicker.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Each entry in InfoTicker.xml is a message that will disply in game.");
                sw.WriteLine("DelayBetweenMessages controls the time before the next message is displayed.");
                sw.WriteLine("Setting Random to true will show the messages in a random order until all have been displayed. The list will repeat again but in a new random order.");
                sw.WriteLine("Leaving Random to false will display each message in order of the list until all have been displayed. The list will repeat.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"InvalidItemKicker\" Enable=\"False\" Ban=\"False\" LevelToIgnore=\"0\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set True or False for Ban");
                sw.WriteLine("Set a numeric value for LevelToIgnore");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a InvalidItems.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Each entry in InvalidItems.xml is checked against each players inventory.");
                sw.WriteLine("If any items in a player's inventory match the invalid items list, a message will show in the server alerting everyone. The player is also kicked.");
                sw.WriteLine("If Ban is set to true it will ban the player instead of kicking them for their illegal items.");
                sw.WriteLine("Setting a LevelToIgnore will ignore all admins and mods based on the ServerAdmin.xml level they are set to.");
                sw.WriteLine("Setting LevelToIgnore to 5 will ignore all admins and mods level 0-5.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"JailCommands\" Enable=\"False\" JailSize=\"4\" JailPosition=\" - 14, 106, -2\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for JailSize");
                sw.WriteLine("Set a numeric value set of x, y, z position for JailPosition");
                sw.WriteLine();
                sw.WriteLine("Enables the jail system for naughty players. This muct be enabled to utilize other tools that send a player to jail.");
                sw.WriteLine("JailSize controls how far a player can stray from the jail before it teleports them back to the JailPosition.");
                sw.WriteLine("JailPosition controls where a jailed player is sent to. This is the x, y, z position.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Killme\" Enable=\"False\" DelayBetweenKillme=\"60\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for DelayBetweenKillme");
                sw.WriteLine();
                sw.WriteLine("Enables the chat command /killme so players can kill themselves.");
                sw.WriteLine("Set the DelayBetweenKillme to control how long a player must wait before /killme will work for them again.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Motd\" Enable=\"False\" ShowOnRespawn=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set True or False for ShowOnRespawn");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a Motd.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Message of the day or Motd entries will show to the player upon joining the server.");
                sw.WriteLine("Each entry in the Motd.xml will show as a separate message in game.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"NewSpawnTele\" Enable=\"False\" NewSpawnTelePosition=\" - 1, 99, -18\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for NewSpawnTelePosition");
                sw.WriteLine();
                sw.WriteLine("Teleports a new player upon joining to the NewSpawnTelePosition.");
                sw.WriteLine("Set NewSpawnTelePosition to control where a new player will spawn to.");
                sw.WriteLine("NewSpawnTelePosition is an x, y, z position.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"NormalPlayerNameColoring\" Enable=\"False\" NormalPlayerPrefix=\"(NOOB)\" NormalPlayerColor=\"[00B3B3]\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a value of your choice in paranthesis for NormalPlayerPrefix");
                sw.WriteLine("Set a color using a html value in brackets for NormalPlayerColor");
                sw.WriteLine();
                sw.WriteLine("Enabling makes all standard players chat message show with a prefix and color.");
                sw.WriteLine("NormalPlayerPrefix controls the prefix for the message.");
                sw.WriteLine("NormalPlayerColor controls the color of the chat message.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"PlayerLogs\" Enable=\"False\" Interval=\"60\" Position=\"False\" Inventory=\"False\" Extra=\"False\" DaysBeforeDeleted=\"5\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for Interval");
                sw.WriteLine("Set True or False for Position");
                sw.WriteLine("Set True or False for Inventory");
                sw.WriteLine("Set True or False for Extra");
                sw.WriteLine("Set a numeric value for DaysBeforeDeleted");
                sw.WriteLine();
                sw.WriteLine("Starts a log that will keep track of any enabled options.");
                sw.WriteLine("Setting the Interval will control how often these checks and logs and written to the file.");
                sw.WriteLine("Position controls whether the current player position, is logged.");
                sw.WriteLine("Inventory controls whether the current player inventory, is logged.");
                sw.WriteLine("Extra controls whether the current player is dead, is logged.");
                sw.WriteLine("Log files will auto delete themselves after a set amount of days. DaysBeforeLogDelete controls the amount of days.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"PlayerStatCheck\" Enable=\"False\" AdminLevel=\"0\" KickEnabled=\"False\" BanEnabled=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for AdminLevel");
                sw.WriteLine("Set True or False for KickEnabled");
                sw.WriteLine("Set True or False for BanEnabled");
                sw.WriteLine();
                sw.WriteLine("Automatically checks if a player has an illegal value for their level, player height, run speed, available skill points, max health, max stamina or max jump height.");
                sw.WriteLine("Detected players who fail any of the checks will have a log created.");
                sw.WriteLine("Setting KickEnabled to true will kick the detected player.");
                sw.WriteLine("Setting BanEnabled to true will ban the detected player.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"ReservedSlots\" Enable=\"False\" ReservedCheck=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set True or False for ReservedCheck");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a ReservedSlots.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Turns on an automatic reservation system. When the server is full, it will kick 1 player that is not listed in the ReservedSlots.xml");
                sw.WriteLine("The auto kick chooses based on the player level, their crafted items, and their distance traveled.");
                sw.WriteLine("Setting ReservedCheck to true enables the chat command /reserved which will respond with the players reservation expiration time.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"SetHome\" Enable=\"False\" SetHome2Enabled=\"False\" SetHome2DonorOnly=\"False\" DelayBetweenSetHomeUses=\"60\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set True or False for SetHome2Enabled");
                sw.WriteLine("Set True or False for SetHome2DonorOnly");
                sw.WriteLine("Set a numeric value for DelayBetweenSetHomeUses");
                sw.WriteLine();
                sw.WriteLine("While enabled, players can use chat command /sethome, /home, and /delhome.");
                sw.WriteLine("/sethome will save the player's current location.");
                sw.WriteLine("/home will teleport the player to their saved home location.");
                sw.WriteLine("/delhome will delete the saved home postion.");
                sw.WriteLine("DelayBetweenSetHomeUses controls the delay before a player can use /home or /home2. This is set in minutes.");
                sw.WriteLine("SetHome2Enabled enables a second home position controlled through chat commands /sethome2, /home2, /delhome2.");
                sw.WriteLine("/sethome2 will save the player's current location.");
                sw.WriteLine("/home2 will teleport the player to their saved home location.");
                sw.WriteLine("/delhome2 will delete the saved home postion.");
                sw.WriteLine("If SetHome2DonorOnly is enabled, only donors on the ReservedSlots.xml with a valid expiration can use /sethome2, /home2, and /delhome2.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"SpecialPlayerNameColoring\" Enable=\"False\" SpecialPlayerSteamId=\"76561191234567891, 76561191987654321\" SpecialPlayerPrefix=\"(SPECIAL)\" SpecialPlayerColor=\"[ADAD85]\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a steam Id value of your choice separated by commas for SpecialPlayerSteamId");
                sw.WriteLine("Set a value of your choice in paranthesis for SpecialPlayerPrefix");
                sw.WriteLine("Set a color using a html value in brackets for SpecialPlayerColor");
                sw.WriteLine();
                sw.WriteLine("Players who have steam id listed under SpecialPlayerSteamId will have a prefix and color applied to their chat messages.");
                sw.WriteLine("Separate the special steam id by commas.");
                sw.WriteLine("Leaving the prefix blank will still show the color but no prefix before their name.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"StartingItems\" Enable=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a StartingItems.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("All items listed in StartingItems.xml will be given to a new player when they first join the server.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Stopserver\" TenSecondCountdownEnabled=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for TenSecondCountdownEnabled");
                sw.WriteLine();
                sw.WriteLine("If console command shutdown is used, the timer will give a warning at ten seconds remaining and a 5 second countdown timer displaying 5, 4, 3, 2, 1 at each remaining second.");
                sw.WriteLine("This will also show during the auto shutdown process.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"TempBan\" Enable=\"False\" AdminLevel=\"0\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for AdminLevel");
                sw.WriteLine();
                sw.WriteLine("This console command bans a player for a small period of time.");
                sw.WriteLine("Enabling allows console command tempban.");
                sw.WriteLine("Type tempban entity Id 1.");
                sw.WriteLine("If you input a value higher than 60, it will default.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Travel\" Enable=\"False\" DelayBetweenUses=\"0\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for DelayBetweenUses");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a TravelLocations.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("All locations listed in the TravelLocations.xml will allow a player to type /travel while inside one and teleport to the corresponding destination.");
                sw.WriteLine("Inside the TravelLocations.xml, xyzMin controls one corner of the travel zone and xyzMax controls the opposite corner. Destination is where the player will teleport to.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"UndergroundCheck\" Enable=\"False\" AdminLevel=\"0\" MaxPing=\"300\" KillPlayer=\"False\" Announce=\"False\" JailEnabled=\"False\" KickEnabled=\"False\" BanEnabled=\"False\" DaysBeforeDeleted=\"5\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for AdminLevel");
                sw.WriteLine("Set a numeric value for MaxPing");
                sw.WriteLine("Set True or False for KillPlayer");
                sw.WriteLine("Set True or False for Announce");
                sw.WriteLine("Set True or False for JailEnabled");
                sw.WriteLine("Set True or False for KickEnabled");
                sw.WriteLine("Set True or False for BanEnabled");
                sw.WriteLine("Set a numeric value for DaysBeforeDeleted");
                sw.WriteLine();
                sw.WriteLine("Automatically checks for players using flight or no clip underground.");
                sw.WriteLine("Detections are written to a log file for admin review.");
                sw.WriteLine("The admin level is the tier a player is ignored by the detection.");
                sw.WriteLine("MaxPing is the ping a player must hit before the detector ignores them. This is to prevent false positives during lag spikes from the player or server.");
                sw.WriteLine("Multiple penalties are available by setting true for the appropriate punishment. All punishments can be enabled for a K.O. punch.");
                sw.WriteLine("Log files will auto delete themselves after a set amount of days. DaysBeforeLogDelete controls the amount of days.");
                sw.WriteLine("*Note* This tool is based around Coppi's mod player underground check and modified for ServerTools and automation.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Voting\" Enable=\"False\" YourVotingSite=\"https://7daystodie-servers.com/server/70267\" APIKey=\"iYNqIvdhDBh8DZDrnw96GanL69aN2OKZIB\" DelayBetweenRewards=\"24\" RewardCount=\"3\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set your server https address value for YourVotingSite. This will match your registered server at https://7daystodie-servers.com");
                sw.WriteLine("Set your server APIKey value found at https://7daystodie-servers.com for APIKey");
                sw.WriteLine("Set a numeric value for DelayBetweenRewards");
                sw.WriteLine("Set a numeric value for RewardCount");
                sw.WriteLine();
                sw.WriteLine("Enabling allows players to use chat command /reward after voting at https://7daystodie-servers.com for your server.");
                sw.WriteLine("If a player has not voted, they will be told to vote at YourVotingSite value.");
                sw.WriteLine("The APIKey is attached to your registered server listed in your server details at https://7daystodie-servers.com");
                sw.WriteLine("DelayBetweenRewards controls how many hours a player must wait before being able to vote and receive a reward for voting.");
                sw.WriteLine("Reward count controls how many items a player will receive from the VoteRewards.xml each time they use /reward.");
                sw.WriteLine("Reward count does not control how many of a particular item you will receive, it controls how many entries from the VoteRewards.xml a player will receive.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"Watchlist\" Enable=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a Watchlist.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("All users Id that matches those listed in the watchlist will trigger an ingame alert to all online admins.");
                sw.WriteLine("This alert message will spam your admins, annoying them until they deal with the player");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"WeatherVote\" Enable=\"False\" VoteDelay=\"30\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set a numeric value for RewardCount");
                sw.WriteLine();
                sw.WriteLine("Enabling will allow players to start a vote to change the weather by typing /weather in chat.");
                sw.WriteLine("All players will be alerted to an open weather vote where they can type /normal, /rain, or /snow.");
                sw.WriteLine("The winning weather type will be announced after 30 seconds and set server wide.");
                sw.WriteLine("VoteDelay controls the time between votes. Time is in minutes.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("<Tool Name=\"ZoneProtection\" Enable=\"False\" KillMurderer=\"False\" JailEnabled=\"False\" KickEnabled=\"False\" BanEnabled=\"False\" ZoneMessage=\"False\" />");
                sw.WriteLine();
                sw.WriteLine("Set True or False for Enable");
                sw.WriteLine("Set True or False for KillMurderer");
                sw.WriteLine("Set True or False for JailEnabled");
                sw.WriteLine("Set True or False for KickEnabled");
                sw.WriteLine("Set True or False for BanEnabled");
                sw.WriteLine("Set True or False for ZoneMessage");
                sw.WriteLine();
                sw.WriteLine("Enabling will create a ZoneProtection.xml in your \"world save folder/ServerTools\"");
                sw.WriteLine("Automatically detects players locations to see if they match those listed in ZoneProtection.xml");
                sw.WriteLine("Players will receive a message alerting them to entering the zone as well as when leaving.");
                sw.WriteLine("This does not stop a player from being able to shoot another depending on the game settings. It will punish any player caught killing another player while protected.");
                sw.WriteLine("It applies to both the killer and victim, if either one are protected, it will be detected.");
                sw.WriteLine("Automatically kills, jails, kicks, or bans the killer depending what is set to true.");
                sw.WriteLine("If jail is enabled, the victim can type /forgive to release the killer from jail.");
                sw.WriteLine("The victim receives a message upon respawn alerting them to type /return. This command brings them back to their death spot.");
                sw.WriteLine("If ZoneMessage is false, players will not receive a message upon entering or exiting a protected zone.");
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine();
                sw.WriteLine("Console commands");
                sw.WriteLine();
                sw.WriteLine("AdminChatColor or acc");
                sw.WriteLine("Example: acc 76561191234567891 off");
                sw.WriteLine("Example: acc 76561191234567891 on");
                sw.WriteLine("Controls the chat color and prefix of admins. Admins can disable their chat color and prefix to stay hidden or stealthy while playing.");
                sw.WriteLine();
                sw.WriteLine("EntityRemove");
                sw.WriteLine("Example: entityremove 12345");
                sw.WriteLine("Removes an existing entity based on its entity id.");
                sw.WriteLine();
                sw.WriteLine("GiveBlock or gb");
                sw.WriteLine("Example: gb 76561191234567891 torch 10");
                sw.WriteLine("Gives a block directly to the player inventory.");
                sw.WriteLine("*Note* This command uses a block of code from Bad Company api manager and has been modified for ServerTools.");
                sw.WriteLine();
                sw.WriteLine("GiveItem or gi");
                sw.WriteLine("Example: gi 76561191234567891 wood 50 1");
                sw.WriteLine("Gives a item directly to the player inventory.");
                sw.WriteLine("*Note* This command uses a block of code from Bad Company api manager and has been modified for ServerTools.");
                sw.WriteLine();
                sw.WriteLine("GiveStartingItmes or gsi");
                sw.WriteLine("Example: gsi 76561191234567891");
                sw.WriteLine("Gives all starting items from the StartingItems.xml to the player and sets a new save point.");
                sw.WriteLine();
                sw.WriteLine("Jail");
                sw.WriteLine("Example: jail add 76561191234567891");
                sw.WriteLine("Example: jail list");
                sw.WriteLine("Sends the player to jail. They will not pass go or collect $200 dollars.");
                sw.WriteLine();
                sw.WriteLine("Maxping");
                sw.WriteLine("Example: maxping 250");
                sw.WriteLine("Sets the maximum ping a player can have.");
                sw.WriteLine();
                sw.WriteLine("Mute");
                sw.WriteLine("Example: mute add 76561191234567891");
                sw.WriteLine("Mutes the player from talking in public chat.");
                sw.WriteLine();
                sw.WriteLine("Shutdown");
                sw.WriteLine("Example: shutdown check");
                sw.WriteLine("Returns the remaining time before the next scheduled shutdown.");
                sw.WriteLine();
                sw.WriteLine("PingImmunity");
                sw.WriteLine("Example: pingimmunity add 76561191234567891");
                sw.WriteLine("Example: pingimmunity remove 76561191234567891");
                sw.WriteLine("Adds the player to the PingImmunity.xml file. Players on this list are not booted for having too high a ping result.");
                sw.WriteLine();
                sw.WriteLine("ReservedSlots");
                sw.WriteLine("Example: reservedslots add 76561191234567891");
                sw.WriteLine("Example: rs remove 76561191234567891");
                sw.WriteLine("Adds the player to the ReservedSlots.xml file. Players on this list are not booted when the server is full and reserved slots are enabled.");
                sw.WriteLine();
                sw.WriteLine("ResetAnimalTracking");
                sw.WriteLine("Example: animaltracking reset 76561191234567891");
                sw.WriteLine("Resets the delay on the command animal tracking for the player.");
                sw.WriteLine();
                sw.WriteLine("ResetFirstClaimBlock");
                sw.WriteLine("Example: firstclaimblock reset 76561191234567891");
                sw.WriteLine("Resets the delay on the command first claim block for the player.");
                sw.WriteLine();
                sw.WriteLine("ResetGimme");
                sw.WriteLine("Example: gimme reset 76561191234567891");
                sw.WriteLine("Resets the delay on the command gimme for the player.");
                sw.WriteLine();
                sw.WriteLine("ResetHome");
                sw.WriteLine("Example: home reset 76561191234567891");
                sw.WriteLine("Resets the delay on the command home and home2 for the player.");
                sw.WriteLine();
                sw.WriteLine("ResetPlayer");
                sw.WriteLine("Example: player reset 76561191234567891");
                sw.WriteLine("Resets the profile for the player.");
                sw.WriteLine();
                sw.WriteLine("ResetVoteReward");
                sw.WriteLine("Example: votereward reset 76561191234567891");
                sw.WriteLine("Resets the delay on the command reward for the player.");
                sw.WriteLine();
                sw.WriteLine("SpawnEntityInRadius");
                sw.WriteLine("Example: ser 76561191234567891 30 @ 62 63 64");
                sw.WriteLine("Spawns a list of entity in a radius around the player.");
                sw.WriteLine();
                sw.WriteLine("StopServer");
                sw.WriteLine("Example: stopserver 5");
                sw.WriteLine("Example: stopserver cancel");
                sw.WriteLine("Stops the server with a count down timer based on the minutes you choose.");
                sw.WriteLine();
                sw.WriteLine("TempBan");
                sw.WriteLine("Example: tempban 12341 30");
                sw.WriteLine("Bans the player based their entity id for small amount of time. Maximum temp ban time is 60 minutes.");
                sw.WriteLine();
                sw.WriteLine("WatchList");
                sw.WriteLine("Example: watchlist add 76561191234567891");
                sw.WriteLine("Example: watchlist remove 76561191234567891");
                sw.WriteLine("Adds a player to the watchlist.");
                sw.Flush();
                sw.Close();
            }
        }
    }
}
